- src/test/java/Ankit/Program10_NonRepetingCharFromString.java
Assignmenst 10
print first non repeating character from a string
> Änkit_Assignment_10_non repetative

- src/test/java/Sarika/Assignment_1_reverseString.java
Adding Sarika folder and created one class
> Sarika-Assignment1

- src/test/java/Ankit/Program6_returnDate.java
Que:-"Write a method which accepts string  ""12-1-1897""  (DD-mm-yyyy)   return the month  
i/p = ""11-09-2002""  out put should be 2002
i/p = ""11-09-1987""  out put should be 1987
"
> ReturnDaateUpdatedProgram

- src/test/java/Sarika/FrequencyOfWord.java
"Frequency of   word in Sentence :    ""Today is monday and today is wonderful day""
day= 4 times
> Assignment 3 is added

- src/test/java/Ankit/Program2_ReverseWord.java
Reverse word Program
i/p : ""Today is the best day""
o/p ""day best the is Today""
> Ankit_Reverse_Word_Program

- pom.xml
- src/test/java/Ankit/Program3_WordisPresenrORNot.java
- src/test/java/Ankit/Program4_EvenORodd.java
- src/test/java/Ankit/Program5_RemoveSpaces.java
- src/test/java/Ankit/Program7_sumOfNumber.java
- src/test/java/Ankit/Program8_MovingAllZero.java
- src/test/java/Ankit/Program9_Anagram2.java
- src/test/java/Ankit/WebDrivermanager.java
> Ankit webdriver manager

- src/test/java/Ankit/Program3_WordisPresenrORNot.java
"write method which return boolean value if  provided word is present in the proivided string :
i/p = ""Todayu is monday""    word is  ""is""    O/p: true word is present
> Ankit_WordPresentOrNot_Program

- src/test/java/Ankit/Program3_WordisPresenrORNot.java
- src/test/java/Ankit/Program4_EvenORodd.java
Program:- write a method which accpets number and print if provided number is even or odd"
> Ankit java assignment4

- src/test/java/Ankit/Program3_WordisPresenrORNot.java
- src/test/java/Ankit/Program4_EvenORodd.java
- src/test/java/Ankit/Program5_RemoveSpaces.java
Program:- Write method which removes spaces from from provided  String
> Ankit java assignment5

- src/test/java/Ankit/Program3_WordisPresenrORNot.java
- src/test/java/Ankit/Program4_EvenORodd.java
- src/test/java/Ankit/Program5_RemoveSpaces.java
- src/test/java/Ankit/Program7_sumOfNumber.java
Program:- Write a method which accepts two int value and return the sum of it.
> Ankit java assignment7

- src/test/java/Ankit/Program3_WordisPresenrORNot.java
- src/test/java/Ankit/Program4_EvenORodd.java
- src/test/java/Ankit/Program5_RemoveSpaces.java
- src/test/java/Ankit/Program7_sumOfNumber.java
- src/test/java/Ankit/Program8_MovingAllZero.java
Program:- move all zeros to end of the array
I/P{5,0,3,6,9,5,0,6,0,3,6}
o/p{0,0,0,5,3,6,9,5,6,3,6,}
"
> Ankit java assignment8

- src/test/java/Ankit/Program3_WordisPresenrORNot.java
- src/test/java/Ankit/Program4_EvenORodd.java
- src/test/java/Ankit/Program5_RemoveSpaces.java
- src/test/java/Ankit/Program7_sumOfNumber.java
- src/test/java/Ankit/Program8_MovingAllZero.java
- src/test/java/Ankit/Program9_Anagram2.java
Program:- check if two String are Anagram
i/p  : keep i/p : peek  o/p : anagram
> Ankit java assignment9

- .classpath
- .settings/org.eclipse.jdt.core.prefs
- src/test/java/Priya/Assgn1_ReverseString.java
Please review the assignnment 1
> Priya_Assgn1

- .classpath
- src/test/java/Sarika/Assignment_1_reverseString.java
- src/test/java/Sarika/Program10_FirstNonRepeatChar.java
- src/test/java/Sarika/Program11_LongestString.java
- src/test/java/Sarika/Program13_SumofeachChar.java
- src/test/java/Sarika/Program14_Sumofdigit.java
- src/test/java/Sarika/Program17_SeparateString.java
- src/test/java/Sarika/Program1_ReverseString.java
- src/test/java/Sarika/Program23_LargestNoarray.java
- src/test/java/Sarika/Program27_RemoveDuplicateEle.java
- src/test/java/Sarika/Program_12_FrequencyOfWord.java
- src/test/java/Sarika/Program_15_Palindrome.java
- src/test/java/Sarika/Program_19_PrimeNumber.java
- src/test/java/Sarika/Program_20_fibonnaci.java
- src/test/java/Sarika/Program_21_SortArray.java
- src/test/java/Sarika/Program_22_LargAndSmallNo.java
- src/test/java/Sarika/Program_25_ShiftEle.java
- src/test/java/Sarika/Program_26_CountVowels.java
- src/test/java/Sarika/Program_2_ReverseWord.java
- src/test/java/Sarika/Program_3_WordIsPresent.java
- src/test/java/Sarika/Program_4_EvenOROdd.java
- src/test/java/Sarika/Program_5_RemoveSpaces.java
- src/test/java/Sarika/Program_6_dates.java
- src/test/java/Sarika/Program_7_SumofInt.java
- src/test/java/Sarika/Program_8_MoveAllZeroes.java
- src/test/java/Sarika/Program_9_anagram.java
- src/test/java/Sarika/Program_FrequencyOfLetter.java
1. String reverse:
way 1. string raw logic
way2: StringBuffer   ... revrese();
String reverse :
i/p=  ""Today is best day""
o/p=""yad tseb si yadoT"""
15.Check provided number is palindrome number
19."to check if the given number is Prime?
i/p  : 97
o/p : true
26."How to calculate the number of vowels and consonants in a string
i/p  : zaddio
o/p : vowels: 3, consonants : 3"
2."i/p : ""Today is best day""
o/p ""day best is Today"""
3."write method which return boolean value if  provided word is present in the proivided string :
i/p = ""Todayu is monday""    word is  ""is""    O/p: true word is present 
i/p = ""Todayu is monday""    word is  ""idds""    O/p: true word NOT is present 
4."write a method which accpets number and print if provided number is even or odd"
5.Write method which …
> Sarika remaining programs

- src/test/java/Ankit/Program11_longestString.java
- src/test/java/Ankit/Program12_duplicatenumberfromarray.java
- src/test/java/Ankit/Program13_SumOfDigitInString.java
- src/test/java/Ankit/Program14_SumOfDigitInString.java
- src/test/java/Ankit/Program15_NumberPalindrome.java
Program:- Check provided number is palindrome number
> Ankit java assignment15 palindrome

- src/test/java/Ankit/Program11_longestString.java
"Write a function to find out longest  in a given string []
i/p  : {“nitin”, “jadeja”, “mama” , “Madam Im Adam”}
o/p : Madam Im Adam
"
> Ankit_FindLongestString_Program

- src/test/java/Ankit/Program11_longestString.java
- src/test/java/Ankit/Program12_duplicatenumberfromarray.java
Program:- Find duplicate elements from an array:
> Ankit java assignment12

- src/test/java/Ankit/Program11_longestString.java
- src/test/java/Ankit/Program12_duplicatenumberfromarray.java
- src/test/java/Ankit/Program13_SumOfDigitInString.java
Program :- Sum of all digits  e.g.  "My age 13 , after 5 years i become 18 years old"   =   1+3+5+1+8=   18
> Ankit java assignment13

- src/test/java/Ankit/Program11_longestString.java
- src/test/java/Ankit/Program12_duplicatenumberfromarray.java
- src/test/java/Ankit/Program13_SumOfDigitInString.java
- src/test/java/Ankit/Program14_SumOfDigitInString.java
Program:- Sum of all digits  e.g.  "My age 13 , after 5 years i become 18 years old"   =  13+5+18=   36
> Ankit java assignment14

- src/test/java/Priya/Assgn1_ReverseString.java
- src/test/java/Priya/Assgn2_ReverseWord.java
> Assgn2 reverse word

- src/test/java/Bhakti/P1.java
Bhakti P1 branch is crested to test conflict
> bhakti_b1_p1

- src/test/java/Bhakti/P1.java
> p1_added same line

- src/test/java/Ankit/Program16_StringPalindrom.java
- src/test/java/Ankit/Program17_SeperateNumAndLetter.java
- src/test/java/Ankit/Program19_PrimeNumber.java
- src/test/java/Ankit/Program20_fibonacciSeriese.java
- src/test/java/Ankit/Program21_sortArrayWithoutPredefinedMethods.java
- src/test/java/Ankit/Program22_SammestAndHigestNumber.java
- src/test/java/Ankit/Program24_DifferenceofSmallAndLargeNumber.java
- src/test/java/Ankit/Program25_shiftelement.java
- src/test/java/Ankit/program23_2ndlargestnumber.java
"Write a program that sort array without using any predefined methods
i/p  : {5,1,2,7,6,3,4,9}
o/p : {1,2,3,4,5,6,7,9}
Program:- How to find the largest and smallest number in an array
i/p  : {5,1,2,7,6,3,4,9}
o/p : small: 1 & highest: 9
Program:- "Find the second lagest number from array 
Program:- Find the difference between largest and smallest number 
Program:- "Write a program on array which shift element by 
i/p  : {5,1,2,7,6,3,4,9}
o/p : {1,2,7,6,3,4,9,5}"
> Ankit java remaining program21 25

- src/test/java/Ankit/Program16_StringPalindrom.java
- src/test/java/Ankit/Program17_SeperateNumAndLetter.java
- src/test/java/Ankit/Program19_PrimeNumber.java
- src/test/java/Ankit/Program20_fibonacciSeriese.java
Program:- Check provided string is palindrome
"Write a program which separate numbers and letters from string
i/p  : h2n9fpn2qk2
o/p : hnfpnqk2922"
Program:-"to check if the given number is Prime?
Program:- Fibonacci series
> Ankit_RemainingJavaProgram

- src/test/java/Ankit/WebDrivermanager_Chromedriver.java
> Ankit_Just_RenameTheClassName

- src/test/java/Bhakti/p1.java
- src/test/java/Bhakti/p2.java
> Bhakti_branch 2_p2class

- src/test/java/Sarika/conflict2.java
> sarika conflict

- src/test/java/Priya/Program3_WordIsPresentOrNot.java
> Priya_Program3_wordPresentOrNot

- src/test/java/Priya/Program4_NumEvenOdd.java
> Priya_Assign4_FindEvenOdd

- src/test/java/Ankit/DEomo_2.java
- src/test/java/Bhakti/A.java
> A calss added as perPAD-23456

- src/test/java/Bhakti/A.java
> A calss added as perPAD-23456 without main updates

- src/test/java/Ankit/Demo_anagramProgram.java
> Ankit DemoAnagramProgram

- src/test/java/Ankit/Demo.java
- src/test/java/Sarika/Sarika_conflict.java
- src/test/java/Sarika/conflict1.java
- src/test/java/Sarika/team1.java
> New conflict1

- src/test/java/Ankit/Program10_NonRepetingCharFromString.java
- src/test/java/Ankit/gitdemoclass.java
> GitDemoAngramProgram

- pom.xml
- src/test/java/Ankit/WriteWebTableDataInExcel.java
> Ankit_WriteWebTableDataInExcel_Program

- pom.xml
- src/test/java/Ankit/ExcelReading.java
Program:- Read Excel Sheet In Selenium
> Ankit_Excel_ReadingCode

- pom.xml
- src/test/java/Ankit/ExcelReading.java
- src/test/java/Ankit/WriteInExcel.java
Program:- Write Data in Excel using Selenium
> Ankit write in excel

- .classpath
- pom.xml
- src/test/java/Ankit/WriteWebTableDataInExcel.java
Main Method was missing in program now added this please merge it.
> WebtableUpdatedCode

- src/main/java/Features/registration.feature
- src/main/java/Runner/runnerClass.java
- src/main/java/StepDefinations/BaseMethods.java
- src/main/java/StepDefinations/ReusableClass.java
- src/main/java/StepDefinations/StepDef.java
- src/main/resources/BaseClass.java
- src/main/resources/Reusable_class.java
- src/test/java/Bhakti/Zoom.java
> NewFramWor for website

- src/main/java/Features/alert.feature
- src/main/java/Runner/runnerClass.java
- src/main/java/StepDefinations/ReusableClass.java
- src/main/java/StepDefinations/StepDef.java
> Bdd cucumber test

- src/test/java/Nilima_23/Assignment1.java
- src/test/java/Nilima_23/Assignment1_ReverseString.java
> Nilima :Assignment1

- src/test/java/Sarika_23/Assignment1.java
- src/test/java/Sarika_23/Assignment1_ReverseString.java
> Assignment1 _ReverseString

- src/test/java/Ankit_23/EvenOrOdd.java
- src/test/java/Ankit_23/ReverseEachWord.java
- src/test/java/Ankit_23/reverseString.java
> Ankit assignment3 even or odd

- src/test/java/Ankit_23/reverseString.java
> Ankit_ReverseString

- src/test/java/Ankit_23/ReverseEachWord.java
- src/test/java/Ankit_23/reverseString.java
> Ankit assignment2 reverse each word

- src/test/java/Ankit_23/EvenOrOdd.java
- src/test/java/Ankit_23/ReverseEachWord.java
- src/test/java/Ankit_23/reverseString.java
> Ankit assignment4 check word is present in/string

- src/test/java/Sarika_23/Assignment1.java
- src/test/java/Sarika_23/Assignment1_ReverseString.java
- src/test/java/Sarika_23/Assignment2_ReverseWord.java
> Sarika reverse word

- src/test/java/Sarika/Program_3_WordIsPresent.java
- src/test/java/Sarika_23/Assignment1.java
- src/test/java/Sarika_23/Assignment1_ReverseString.java
- src/test/java/Sarika_23/Assignment2_ReverseWord.java
- src/test/java/Sarika_23/Assignment3_WordIsPresent.java
> Assignment3 word is present

- src/test/java/Sarika/Program_3_WordIsPresent.java
- src/test/java/Sarika_23/Assignment1.java
- src/test/java/Sarika_23/Assignment1_ReverseString.java
- src/test/java/Sarika_23/Assignment2_ReverseWord.java
- src/test/java/Sarika_23/Assignment3_WordIsPresent.java
- src/test/java/Sarika_23/Assignment4_EvenOrOdd.java
> Assignment4 even or odd

- src/test/java/Nilima_23/Assignment1_ReverseString.java
- src/test/java/Nilima_23/Assignment2_ReverseStringWord.java
- src/test/java/Nilima_23/Assignment3_ReverseStringWordisPresenrORNot.java
- src/test/java/Nilima_23/Assignment4_EvenOdd.java
- src/test/java/Nilima_23/Assignment5_RemoveSpace.java
> Nilima assignment5 remove space

- src/test/java/Nilima_23/Assignment1_ReverseString.java
- src/test/java/Nilima_23/Assignment2_ReverseStringWord.java
- src/test/java/Nilima_23/Assignment3_ReverseStringWordisPresenrORNot.java
> Nilima assignment3 ReverseStringWordisPresenrORNot

- src/test/java/Nilima_23/Assignment1_ReverseString.java
- src/test/java/Nilima_23/Assignment2_ReverseStringWord.java
- src/test/java/Nilima_23/Assignment3_ReverseStringWordisPresenrORNot.java
- src/test/java/Nilima_23/Assignment4_EvenOdd.java
> Nilima assignment4

- src/test/java/Nilima_23/Assignment1_ReverseString.java
- src/test/java/Nilima_23/Assignment2_ReverseStringWord.java
- src/test/java/Nilima_23/Assignment3_ReverseStringWordisPresenrORNot.java
- src/test/java/Nilima_23/Assignment4_EvenOdd.java
- src/test/java/Nilima_23/Assignment5_RemoveSpace.java
- src/test/java/Nilima_23/Assignment7_Addition.java
- src/test/java/Nilima_23/Assignment8_MoveZeroAtEnd.java
> Nilima assignment8 move all zero at end

- src/test/java/Nilima_23/Assignment1_ReverseString.java
- src/test/java/Nilima_23/Assignment2_ReverseStringWord.java
- src/test/java/Nilima_23/Assignment3_ReverseStringWordisPresenrORNot.java
- src/test/java/Nilima_23/Assignment4_EvenOdd.java
- src/test/java/Nilima_23/Assignment5_RemoveSpace.java
- src/test/java/Nilima_23/Assignment7_Addition.java
> Nilima assignment7 sum of two int

- src/test/java/Ankit_23/reverseString.java
> Udated_REverse_String_Ankit

- src/test/java/Rupesh_23/ReverseString.java
- src/test/java/Rupesh_23/Reversestring_byword.java
- src/test/java/Rupesh_23/even_odd_program.java
> Revesrs string byword

- src/test/java/Rupesh_23/ReverseString.java
> Rupesh_revesrsestring

- src/test/java/Rupesh_23/ReverseString.java
- src/test/java/Rupesh_23/even_odd_program.java
> Assignment even odd program

- .classpath
- src/test/java/Nilima_23/Assignment1_ReverseString.java
- src/test/java/Nilima_23/Assignment2_ReverseStringWord.java
> Nilima :Assignment 2 String word revsere

- src/main/java/Constent/locators.java
- src/main/java/Features/windows.feature
- src/main/java/Runner/runnerClass.java
- src/main/java/StepDefinations/StepDef.java
> Multiwindows

- src/test/java/Rupesh_23/remove_spaces_from_string.java
> remove_spaces_from_string

- src/test/java/Nilima_23/Assignment1_ReverseString.java
- src/test/java/Nilima_23/Assignment2_ReverseStringWord.java
- src/test/java/Nilima_23/Assignment3_ReverseStringWordisPresenrORNot.java
- src/test/java/Nilima_23/Assignment4_EvenOdd.java
- src/test/java/Nilima_23/Assignment7_Addition.java
- src/test/java/Nilima_23/Assignment8_MoveZeroAtEnd.java
- src/test/java/Nilima_23/Assignmnet9_AnagramString.java
> Nilima Assignment 9 Anagram String
